/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.fundacionjala.salesforce;

import org.fundacionjala.salesforce.core.config.PropertiesSetter;
import org.fundacionjala.salesforce.core.config.TestExecutionProperties;
import org.fundacionjala.salesforce.core.selenium.WebDriverManager;
import org.fundacionjala.salesforce.core.throwables.PropertiesReadingException;
import org.openqa.selenium.WebDriver;
import org.testng.annotations.*;

import java.io.IOException;

import static org.testng.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting()  {
        WebDriverManager webDriverManager = new 
    }
}
